{{- range $name, $svc := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: pulselens-{{ $name }}
spec:
  selector:
    app: pulselens-{{ $name }}
  ports:
    - port: {{ $svc.port }}
      targetPort: {{ $svc.port }}
---
{{- end }}

